[package]
name = "sigap-queue-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
prost = "0.13"
sqlx = { version = "0.8", features = ["runtime-tokio", "postgres", "macros", "uuid", "chrono"] }
serde = { version = "1", features = ["derive"] }

[build-dependencies]
tonic-build = "0.12"
