// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.26.1
// source: sigap/queue_engine.proto

package queueenginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueueEngine_GenerateQueueNumber_FullMethodName = "/sigap.queue_engine.QueueEngine/GenerateQueueNumber"
)

// QueueEngineClient is the client API for QueueEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// QueueEngine is the gRPC service implemented by the Rust microservice.
// It owns the dynamic, high-safety logic for queue number generation and bed synchronization.
type QueueEngineClient interface {
	// GenerateQueueNumber performs atomic daily counter, patient handling,
	// ticket creation and returns the formatted nomor antrean.
	// Called by the Go API gateway.
	GenerateQueueNumber(ctx context.Context, in *GenerateQueueRequest, opts ...grpc.CallOption) (*GenerateQueueResponse, error)
}

type queueEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueEngineClient(cc grpc.ClientConnInterface) QueueEngineClient {
	return &queueEngineClient{cc}
}

func (c *queueEngineClient) GenerateQueueNumber(ctx context.Context, in *GenerateQueueRequest, opts ...grpc.CallOption) (*GenerateQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateQueueResponse)
	err := c.cc.Invoke(ctx, QueueEngine_GenerateQueueNumber_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueEngineServer is the server API for QueueEngine service.
// All implementations must embed UnimplementedQueueEngineServer
// for forward compatibility.
//
// QueueEngine is the gRPC service implemented by the Rust microservice.
// It owns the dynamic, high-safety logic for queue number generation and bed synchronization.
type QueueEngineServer interface {
	// GenerateQueueNumber performs atomic daily counter, patient handling,
	// ticket creation and returns the formatted nomor antrean.
	// Called by the Go API gateway.
	GenerateQueueNumber(context.Context, *GenerateQueueRequest) (*GenerateQueueResponse, error)
	mustEmbedUnimplementedQueueEngineServer()
}

// UnimplementedQueueEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueueEngineServer struct{}

func (UnimplementedQueueEngineServer) GenerateQueueNumber(context.Context, *GenerateQueueRequest) (*GenerateQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateQueueNumber not implemented")
}
func (UnimplementedQueueEngineServer) mustEmbedUnimplementedQueueEngineServer() {}
func (UnimplementedQueueEngineServer) testEmbeddedByValue()                     {}

// UnsafeQueueEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueEngineServer will
// result in compilation errors.
type UnsafeQueueEngineServer interface {
	mustEmbedUnimplementedQueueEngineServer()
}

func RegisterQueueEngineServer(s grpc.ServiceRegistrar, srv QueueEngineServer) {
	// If the following call panics, it indicates UnimplementedQueueEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueueEngine_ServiceDesc, srv)
}

func _QueueEngine_GenerateQueueNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueEngineServer).GenerateQueueNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueEngine_GenerateQueueNumber_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueEngineServer).GenerateQueueNumber(ctx, req.(*GenerateQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueEngine_ServiceDesc is the grpc.ServiceDesc for QueueEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sigap.queue_engine.QueueEngine",
	HandlerType: (*QueueEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateQueueNumber",
			Handler:    _QueueEngine_GenerateQueueNumber_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sigap/queue_engine.proto",
}
