// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: sigap/queue_engine.proto

package queueenginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FacilityId    string                 `protobuf:"bytes,1,opt,name=facility_id,json=facilityId,proto3" json:"facility_id,omitempty"`
	Patient       *PatientInfo           `protobuf:"bytes,2,opt,name=patient,proto3" json:"patient,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQueueRequest) Reset() {
	*x = GenerateQueueRequest{}
	mi := &file_sigap_queue_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQueueRequest) ProtoMessage() {}

func (x *GenerateQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sigap_queue_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQueueRequest.ProtoReflect.Descriptor instead.
func (*GenerateQueueRequest) Descriptor() ([]byte, []int) {
	return file_sigap_queue_engine_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQueueRequest) GetFacilityId() string {
	if x != nil {
		return x.FacilityId
	}
	return ""
}

func (x *GenerateQueueRequest) GetPatient() *PatientInfo {
	if x != nil {
		return x.Patient
	}
	return nil
}

type PatientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender        *string                `protobuf:"bytes,3,opt,name=gender,proto3,oneof" json:"gender,omitempty"`                                // "L" or "P"
	DateOfBirth   *string                `protobuf:"bytes,4,opt,name=date_of_birth,json=dateOfBirth,proto3,oneof" json:"date_of_birth,omitempty"` // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatientInfo) Reset() {
	*x = PatientInfo{}
	mi := &file_sigap_queue_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatientInfo) ProtoMessage() {}

func (x *PatientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_sigap_queue_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatientInfo.ProtoReflect.Descriptor instead.
func (*PatientInfo) Descriptor() ([]byte, []int) {
	return file_sigap_queue_engine_proto_rawDescGZIP(), []int{1}
}

func (x *PatientInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *PatientInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PatientInfo) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *PatientInfo) GetDateOfBirth() string {
	if x != nil && x.DateOfBirth != nil {
		return *x.DateOfBirth
	}
	return ""
}

type GenerateQueueResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TicketId             string                 `protobuf:"bytes,1,opt,name=ticket_id,json=ticketId,proto3" json:"ticket_id,omitempty"`
	FormattedNumber      string                 `protobuf:"bytes,2,opt,name=formatted_number,json=formattedNumber,proto3" json:"formatted_number,omitempty"` // e.g. "RSK-0042"
	Status               string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                          // waiting | ...
	RegisteredAt         string                 `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`          // RFC3339
	EstimatedWaitMinutes int32                  `protobuf:"varint,5,opt,name=estimated_wait_minutes,json=estimatedWaitMinutes,proto3" json:"estimated_wait_minutes,omitempty"`
	ProcessingTimeMicros int64                  `protobuf:"varint,6,opt,name=processing_time_micros,json=processingTimeMicros,proto3" json:"processing_time_micros,omitempty"` // Micro-second (µs) latency of the atomic transaction inside the Rust engine (for traceability)
	Signature            string                 `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`                                                     // SHA-256 hex signature of the visit (immutable proof for Health Wallet)
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GenerateQueueResponse) Reset() {
	*x = GenerateQueueResponse{}
	mi := &file_sigap_queue_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQueueResponse) ProtoMessage() {}

func (x *GenerateQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sigap_queue_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQueueResponse.ProtoReflect.Descriptor instead.
func (*GenerateQueueResponse) Descriptor() ([]byte, []int) {
	return file_sigap_queue_engine_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateQueueResponse) GetTicketId() string {
	if x != nil {
		return x.TicketId
	}
	return ""
}

func (x *GenerateQueueResponse) GetFormattedNumber() string {
	if x != nil {
		return x.FormattedNumber
	}
	return ""
}

func (x *GenerateQueueResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GenerateQueueResponse) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

func (x *GenerateQueueResponse) GetEstimatedWaitMinutes() int32 {
	if x != nil {
		return x.EstimatedWaitMinutes
	}
	return 0
}

func (x *GenerateQueueResponse) GetProcessingTimeMicros() int64 {
	if x != nil {
		return x.ProcessingTimeMicros
	}
	return 0
}

var File_sigap_queue_engine_proto protoreflect.FileDescriptor

const file_sigap_queue_engine_proto_rawDesc = "" +
	"\n" +
	"\x18sigap/queue_engine.proto\x12\x12sigap.queue_engine\"r\n" +
	"\x14GenerateQueueRequest\x12\x1f\n" +
	"\vfacility_id\x18\x01 \x01(\tR\n" +
	"facilityId\x129\n" +
	"\apatient\x18\x02 \x01(\v2\x1f.sigap.queue_engine.PatientInfoR\apatient\"\xa3\x01\n" +
	"\vPatientInfo\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x1b\n" +
	"\x06gender\x18\x03 \x01(\tH\x00R\x06gender\x88\x01\x01\x12'\n" +
	"\rdate_of_birth\x18\x04 \x01(\tH\x01R\vdateOfBirth\x88\x01\x01B\t\n" +
	"\a_genderB\x10\n" +
	"\x0e_date_of_birth\"\x88\x02\n" +
	"\x15GenerateQueueResponse\x12\x1b\n" +
	"\tticket_id\x18\x01 \x01(\tR\bticketId\x12)\n" +
	"\x10formatted_number\x18\x02 \x01(\tR\x0fformattedNumber\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\tR\fregisteredAt\x124\n" +
	"\x16estimated_wait_minutes\x18\x05 \x01(\x05R\x14estimatedWaitMinutes\x124\n" +
	"\x16processing_time_micros\x18\x06 \x01(\x03R\x14processingTimeMicros2y\n" +
	"\vQueueEngine\x12j\n" +
	"\x13GenerateQueueNumber\x12(.sigap.queue_engine.GenerateQueueRequest\x1a).sigap.queue_engine.GenerateQueueResponseBIZGgithub.com/sigap/sigap/apps/api/internal/pb/queueenginepb;queueenginepbb\x06proto3"

var (
	file_sigap_queue_engine_proto_rawDescOnce sync.Once
	file_sigap_queue_engine_proto_rawDescData []byte
)

func file_sigap_queue_engine_proto_rawDescGZIP() []byte {
	file_sigap_queue_engine_proto_rawDescOnce.Do(func() {
		file_sigap_queue_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sigap_queue_engine_proto_rawDesc), len(file_sigap_queue_engine_proto_rawDesc)))
	})
	return file_sigap_queue_engine_proto_rawDescData
}

var file_sigap_queue_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sigap_queue_engine_proto_goTypes = []any{
	(*GenerateQueueRequest)(nil),  // 0: sigap.queue_engine.GenerateQueueRequest
	(*PatientInfo)(nil),           // 1: sigap.queue_engine.PatientInfo
	(*GenerateQueueResponse)(nil), // 2: sigap.queue_engine.GenerateQueueResponse
}
var file_sigap_queue_engine_proto_depIdxs = []int32{
	1, // 0: sigap.queue_engine.GenerateQueueRequest.patient:type_name -> sigap.queue_engine.PatientInfo
	0, // 1: sigap.queue_engine.QueueEngine.GenerateQueueNumber:input_type -> sigap.queue_engine.GenerateQueueRequest
	2, // 2: sigap.queue_engine.QueueEngine.GenerateQueueNumber:output_type -> sigap.queue_engine.GenerateQueueResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sigap_queue_engine_proto_init() }
func file_sigap_queue_engine_proto_init() {
	if File_sigap_queue_engine_proto != nil {
		return
	}
	file_sigap_queue_engine_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sigap_queue_engine_proto_rawDesc), len(file_sigap_queue_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sigap_queue_engine_proto_goTypes,
		DependencyIndexes: file_sigap_queue_engine_proto_depIdxs,
		MessageInfos:      file_sigap_queue_engine_proto_msgTypes,
	}.Build()
	File_sigap_queue_engine_proto = out.File
	file_sigap_queue_engine_proto_goTypes = nil
	file_sigap_queue_engine_proto_depIdxs = nil
}
