import type { Page } from '@playwright/test';
import { expect, test } from './support/test';

/**
 * Phase 3B3 browser coverage: the four citizen transactions, end to end.
 *
 * These are the authoritative happy paths. Everything asserted here is backed
 * by the Go API and the seeded database reached through the same-origin
 * proxy — no request is intercepted, no response is faked, and no fixture
 * stands in for the network. `scripts/dev/Start-LocalE2E.ps1` is the approved
 * way to bring the stack up, and the loopback-only guard in
 * playwright.config.ts rejects any other target before a browser launches.
 *
 * The split with the unit suites is deliberate. Provoking a real 409 needs a
 * fully booked schedule, a real 429 needs an exhausted daily limiter, and a
 * real 401 needs a wrong code against a live booking. Those state-to-copy
 * mappings are deterministic, so they are covered in
 * checkin-flows.test.ts and walkin-flows.test.ts where each case is named and
 * cheap. What those suites cannot prove is that the pieces fit together: that
 * the code the booking page hands the citizen actually redeems at the check-in
 * page, and that the queue number check-in returns is one the status page will
 * accept. That is what this file is for, and it is why the tests share state
 * in sequence rather than each standing up their own data.
 *
 * The order is the journey: A books, B checks in with the code A produced, C
 * looks up the result, D registers a walk-in. `test.describe.serial` is what
 * makes that ordering real, and why B and C read values produced by A.
 */

const MOBILE = { width: 390, height: 844 };
const DESKTOP = { width: 1440, height: 900 };

/** Waits longer than the default: each step here is a real round trip. */
const SETTLE = { timeout: 15_000 };

/** The five public fields the catalog projection is allowed to return. */
interface WireFacility {
	id: string;
	name: string;
	short_code: string;
	type: 'puskesmas' | 'rumah_sakit';
	is_active: boolean;
}

interface WireServiceUnit {
	id: string;
	facility_id: string;
	name: string;
	code: string;
	is_active: boolean;
}

/**
 * Read the public catalog exactly as the browser does, through the proxy.
 *
 * Reading the wire rather than scraping the DOM is what makes these tests
 * independent of the seed's contents. Facility names, counts, and service
 * unit names are all derived from what the API actually returned, so an
 * edited seed changes the test data rather than breaking it — and a field
 * that stopped being sent would fail here, which a DOM assertion could not
 * distinguish from a renamed label.
 */
async function readFacilities(page: Page): Promise<WireFacility[]> {
	const response = await page.request.get('/api/v1/public/facilities');
	expect(response.status(), 'the public catalog must not require a session').toBe(200);
	const body = (await response.json()) as { success: boolean; data: WireFacility[] | null };
	expect(body.success).toBe(true);
	return body.data ?? [];
}

async function readServiceUnits(
	page: Page,
	facilityId: string
): Promise<WireServiceUnit[]> {
	const response = await page.request.get(
		`/api/v1/public/service-units?facility_id=${facilityId}`
	);
	expect(response.status()).toBe(200);
	const body = (await response.json()) as { success: boolean; data: WireServiceUnit[] | null };
	expect(body.success).toBe(true);
	return body.data ?? [];
}

/**
 * A datetime-local value in the future, formatted as the control expects.
 *
 * The control yields a zoneless local string (`YYYY-MM-DDTHH:mm`), so this
 * builds one rather than reusing an ISO string with a Z, which the control
 * would reject. Two days out so the booking cannot race the clock, and the
 * minute is fixed to avoid landing on a boundary the backend treats as
 * closed.
 */
function futureLocalDateTime(): string {
	const when = new Date();
	when.setDate(when.getDate() + 2);
	when.setHours(9, 30, 0, 0);
	const pad = (n: number) => String(n).padStart(2, '0');
	return (
		`${when.getFullYear()}-${pad(when.getMonth() + 1)}-${pad(when.getDate())}` +
		`T${pad(when.getHours())}:${pad(when.getMinutes())}`
	);
}

/**
 * State carried between the serial scenarios.
 *
 * `appointmentId` and `checkinCode` come from A and are the whole point of B
 * existing: the deep link is generated by the booking page, not assembled by
 * this test, so B proves the two pages agree on the contract rather than
 * proving that a hand-built URL works.
 */
const journey = {
	facilityId: '',
	facilityName: '',
	appointmentId: '',
	checkinCode: '',
	queueNumber: ''
};

/**
 * A phone number unique per call, so the daily limiter never interferes.
 *
 * The backend allows 2 queue registrations per phone per facility per day
 * (queue.go, NewDailyLimiter(2)), and the limiter is in-memory in the API
 * process, so it survives across test runs within one stack lifetime. A
 * counter that increments per call is therefore the right shape: a timestamp
 * alone would collide if two calls landed in the same second, which is
 * exactly what a retry does.
 *
 * The result is trimmed to 15 digits because the frontend requires 10-15 and
 * the backend accepts what it is given.
 */
let phoneSequence = 0;
function uniquePhone(): string {
	phoneSequence += 1;
	const stamp = Date.now().toString().slice(-6);
	return `081${String(phoneSequence).padStart(2, '0')}${stamp}`.slice(0, 15);
}

/** Fails the test if the document scrolls sideways at the current width. */
async function expectNoHorizontalOverflow(page: Page) {
	const overflow = await page.evaluate(() => ({
		scrollWidth: document.documentElement.scrollWidth,
		clientWidth: document.documentElement.clientWidth
	}));
	expect(
		overflow.scrollWidth,
		`content is ${overflow.scrollWidth}px wide in a ${overflow.clientWidth}px viewport`
	).toBeLessThanOrEqual(overflow.clientWidth + 1);
}

/** Proves the last thing on a long page is not hidden behind the fixed bar. */
async function expectContentClearsBottomNav(page: Page) {
	const clearance = await page.evaluate(() => {
		const nav = document.querySelector('.sigap-bottom-nav');
		const main = document.querySelector('.sigap-citizen-main');
		if (!nav || !main) return null;
		return {
			mainPaddingBottom: parseFloat(getComputedStyle(main).paddingBottom) || 0,
			navHeight: nav.getBoundingClientRect().height
		};
	});
	expect(clearance, 'the bottom nav and main must both exist').not.toBeNull();
	if (!clearance) return;
	expect(clearance.mainPaddingBottom).toBeGreaterThanOrEqual(clearance.navHeight);
}

/**
 * The four transactions, in the order a citizen performs them.
 *
 * ONE serial group rather than four. `describe.serial` only sequences tests
 * within a single group, and `fullyParallel: true` in playwright.config.ts
 * schedules separate groups against different workers. Four separate
 * describe.serial blocks therefore ran CONCURRENTLY, which is not obvious from
 * the file and produced a baffling failure: D tried to select a facility whose
 * id was still an empty string, because A had not run yet.
 *
 * An empty string happens to match the placeholder `<option value="">`, so the
 * select silently chose the placeholder and then reported "option being
 * selected is not enabled" — an error that points at the walk-in form when the
 * real cause was scheduling three groups away.
 *
 * Grouping them also means a failure in one step stops the rest, which is the
 * behaviour the journey wants: B is meaningless without a code from A, and
 * should report as skipped rather than as a confusing error of its own.
 */
test.describe.serial('the citizen transactions, end to end', () => {
/**
 * A. Booking, from the catalog to a check-in code.
 *
 * The journey a real citizen takes, and the one the design specifies: land on
 * /faskes, pick a facility, and arrive at the booking form with that facility
 * already chosen. Choosing the facility by clicking rather than by navigating
 * to a hand-written URL is what proves the query parameter the catalog link
 * emits is the one the booking page reads.
 */
test.describe('A. booking', () => {
	test.use({ viewport: DESKTOP });

	test('creates an appointment and hands back a check-in code', async ({ page }) => {
		// Start where a citizen starts.
		await page.goto('/faskes');
		const rows = page.locator('#sigap-facility-results li');
		await expect(rows.first()).toBeVisible(SETTLE);

		const wire = await readFacilities(page);
		expect(wire.length, 'the local seed must contain facilities').toBeGreaterThan(0);

		// Only a facility that actually publishes service units can be booked,
		// so the choice is derived from the data rather than assumed. Booking
		// step 2 has nothing to show otherwise, and the failure would look like
		// a frontend bug rather than an unsuitable seed row.
		let chosen: WireFacility | undefined;
		for (const facility of wire) {
			const units = await readServiceUnits(page, facility.id);
			if (units.length > 0) {
				chosen = facility;
				journey.facilityId = facility.id;
				journey.facilityName = facility.name;
				break;
			}
		}
		test.skip(!chosen, 'the local seed has no facility with published service units');
		expect(chosen, 'a bookable facility must exist').toBeTruthy();

		// Click through from the catalog rather than deep-linking, so the
		// facility_id the catalog link emits is the one under test.
		const bookingLink = rows
			.filter({ hasText: chosen!.name })
			.first()
			.getByRole('link');
		await expect(bookingLink).toHaveAttribute('href', /\/appointments\/new\?facility_id=/);
		await bookingLink.click();

		await expect(page).toHaveURL(/\/appointments\/new\?facility_id=/);
		await expect(page.getByRole('heading', { level: 1 })).toBeVisible();

		// Step 1 is satisfied by arriving: the facility is preselected.
		const facilitySelect = page.locator('#sigap-booking-facility_id');
		await expect(facilitySelect).toHaveValue(chosen!.id);

		// Step 2: a real service unit belonging to THIS facility. The units
		// come from the API, so a mismatched pair cannot be submitted by
		// accident — and if the page offered a unit from another facility, the
		// equality below would fail rather than silently posting a bad pair.
		const units = await readServiceUnits(page, chosen!.id);
		const unitSelect = page.locator('#sigap-booking-service_unit_id');
		await expect(unitSelect.locator('option')).toHaveCount(units.length + 1, SETTLE);
		await unitSelect.selectOption(units[0].id);

		// Step 3: a future time and the patient's details.
		await page.locator('#sigap-booking-appointment_time').fill(futureLocalDateTime());
		await page.locator('#sigap-booking-patient_display_name').fill('Siti Rahayu');
		await page.locator('#sigap-booking-patient_phone').fill(uniquePhone());

		// The two-column layout puts the summary beside the form on desktop,
		// and the summary must be reflecting the live selection before submit.
		await expect(page.locator('.sigap-booking-summary')).toBeVisible();
		await expect(page.locator('.sigap-booking-summary')).toContainText(chosen!.name);

		await page.getByRole('button', { name: /Daftar Janji Temu/ }).click();

		// The real backend accepted it. The success panel carries the code,
		// so its appearance is the proof — there is no fixture to satisfy.
		const codeEl = page.locator('[data-testid="booking-checkin-code"]');
		await expect(codeEl).toBeVisible(SETTLE);
		journey.checkinCode = ((await codeEl.textContent()) ?? '').trim();
		expect(journey.checkinCode.length, 'a check-in code must be returned').toBeGreaterThan(4);

		// The deep link is the handoff to B. It must use the canonical
		// parameter names, so the two pages cannot drift apart on a rename.
		const deepLink = page.locator('.sigap-booking__cta');
		await expect(deepLink).toBeVisible();
		const href = (await deepLink.getAttribute('href')) ?? '';
		expect(href).toContain('/appointments/check-in?');
		const params = new URL(href, 'http://local').searchParams;
		expect(params.get('checkin_code')).toBe(journey.checkinCode);
		expect(params.get('appointment_id')).toBeTruthy();
		journey.appointmentId = params.get('appointment_id') ?? '';
		expect(journey.appointmentId).toMatch(
			/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
		);

		// The appointment id the page displays is the same one it links with,
		// so the details block cannot disagree with the handoff.
		await expect(page.locator('[data-testid="booking-appointment-id"]')).toHaveText(
			journey.appointmentId
		);
	});

	test('confirmation is understandable without colour, and the code is selectable', async ({
		page
	}) => {
		// Booking created its own appointment, so re-create one rather than
		// depending on the previous test's state surviving.
		await page.goto(`/appointments/new?facility_id=${journey.facilityId}`);
		const units = await readServiceUnits(page, journey.facilityId);
		await page.locator('#sigap-booking-service_unit_id').selectOption(units[0].id);
		await page.locator('#sigap-booking-appointment_time').fill(futureLocalDateTime());
		await page.locator('#sigap-booking-patient_display_name').fill('Dewi Lestari');
		await page.locator('#sigap-booking-patient_phone').fill(uniquePhone());
		await page.getByRole('button', { name: /Daftar Janji Temu/ }).click();

		const codeEl = page.locator('[data-testid="booking-checkin-code"]');
		await expect(codeEl).toBeVisible(SETTLE);

		// Readable without colour: the panel states the outcome in words, not
		// only as a tinted border. A citizen who cannot distinguish the accent
		// colour still has to be able to tell success from failure.
		const panel = page.locator('.sigap-booking__confirmation');
		await expect(panel.locator('[role="status"]').first()).toBeVisible();
		await expect(panel).toContainText(/berhasil/i);

		// Selectable, because the alternative is retyping a code that may
		// contain characters easy to mistype. The check is computed style
		// rather than a source grep because jsdom does not apply Svelte's
		// scoped styles and a real browser is the only place this is true.
		const userSelect = await codeEl.evaluate(
			(el) => getComputedStyle(el).userSelect || getComputedStyle(el).webkitUserSelect
		);
		expect(['all', 'text']).toContain(userSelect);

		// And a copy affordance exists, since selection is not always possible
		// on a phone.
		await expect(page.getByRole('button', { name: /Salin kode/ })).toBeVisible();
	});
});

/**
 * B. Check-in, using the link A generated.
 *
 * The single most important test in this file. It is the one place where two
 * independently written pages have to agree: the booking page mints an
 * identifier and a code, and the check-in page redeems them. A test that
 * hand-built its own deep link would pass even if the booking page emitted a
 * different parameter name, and the citizen would still be stranded.
 */
test.describe('B. check-in', () => {
	test.use({ viewport: DESKTOP });

	test('the generated deep link prefills and returns a queue ticket', async ({ page }) => {
		test.skip(!journey.checkinCode, 'A must produce a check-in code first');

		const href = `/appointments/check-in?appointment_id=${journey.appointmentId}&checkin_code=${journey.checkinCode}`;
		await page.goto(href);

		// Both fields arrive filled. A deep link that arrives empty is the
		// classic failure of this page: the link works, it just asks for
		// everything again.
		await expect(page.locator('#sigap-checkin-appointment_id')).toHaveValue(
			journey.appointmentId
		);
		await expect(page.locator('#sigap-checkin-checkin_code')).toHaveValue(
			journey.checkinCode
		);

		await page.getByRole('button', { name: /^Check-In$/ }).click();

		// The real backend issued a ticket.
		const ticketNumber = page.locator('[data-testid="queue-number"]');
		await expect(ticketNumber).toBeVisible(SETTLE);
		journey.queueNumber = ((await ticketNumber.textContent()) ?? '').trim();
		expect(journey.queueNumber.length, 'a formatted queue number must be shown').toBeGreaterThan(0);

		// The estimate is labelled as an estimate. The backend computes
		// estimated_wait_minutes once at generation and never recomputes it,
		// so presenting it as current would be a claim the system cannot keep.
		const body = ((await page.locator('body').textContent()) ?? '').toLowerCase();
		expect(body).toContain('estimasi');
		for (const forbidden of ['realtime', 'real-time', 'live', 'dipastikan', 'pasti']) {
			expect(body, `the ticket must not claim ${forbidden}`).not.toContain(forbidden);
		}

		// The way onward.
		await expect(
			page.getByRole('link', { name: /Cek status kunjungan/i })
		).toHaveAttribute('href', '/patient/status');
	});

	test('a wrong check-in code is a wrong code, not a sign-in prompt', async ({ page }) => {
		/*
		 * Books its own appointment rather than reusing the one B checked in.
		 *
		 * That reuse was a real bug in this test: the first B test consumed its
		 * appointment, so by the time this ran the record was already `queued`
		 * and the backend answered 409, not 401. The assertion then failed
		 * looking for an error that was correctly absent — and a retry of the
		 * whole suite flipped between the two, which is the worst possible
		 * failure mode for a test meant to pin down one specific status.
		 *
		 * So the wrong-code case gets a fresh, un-checked-in appointment, and
		 * 401 is genuinely what the backend will answer.
		 */
		await page.goto(`/appointments/new?facility_id=${journey.facilityId}`);
		const units = await readServiceUnits(page, journey.facilityId);
		await page.locator('#sigap-booking-service_unit_id').selectOption(units[0].id);
		await page.locator('#sigap-booking-appointment_time').fill(futureLocalDateTime());
		await page.locator('#sigap-booking-patient_display_name').fill('Andi Pratama');
		await page.locator('#sigap-booking-patient_phone').fill(uniquePhone());
		await page.getByRole('button', { name: /Daftar Janji Temu/ }).click();
		await expect(page.locator('[data-testid="booking-checkin-code"]')).toBeVisible(SETTLE);

		const href = (await page.locator('.sigap-booking__cta').getAttribute('href')) ?? '';
		const freshId = new URL(href, 'http://local').searchParams.get('appointment_id') ?? '';
		expect(freshId).toBeTruthy();

		await page.goto(
			`/appointments/check-in?appointment_id=${freshId}&checkin_code=WRONGCODE123`
		);
		await expect(page.locator('#sigap-checkin-checkin_code')).toHaveValue('WRONGCODE123');
		await page.getByRole('button', { name: /^Check-In$/ }).click();

		// The backend answers 401 here, and on a PUBLIC route that means the
		// code was wrong. Rendering a login prompt would be a serious
		// misreading: the citizen is not signed out, they mistyped a code, and
		// sending them to a login form is a dead end that also implies they
		// need an account for a public service.
		const error = page.locator('[data-testid="checkin-error"]');
		await expect(error).toBeVisible(SETTLE);

		const text = ((await error.textContent()) ?? '').toLowerCase();
		for (const forbidden of [
			'masuk',
			'login',
			'tidak terautentikasi',
			'unauthenticated',
			'sesi',
			'session'
		]) {
			expect(text, `a 401 must not read as an auth state: found "${forbidden}"`).not.toMatch(
				new RegExp(`\\b${forbidden}\\b`)
			);
		}

		// And there is no sign-in control INSIDE the error, because there is
		// nothing to sign into for this route.
		//
		// Scoped to the error region on purpose. The citizen shell's account
		// menu legitimately offers "Masuk" on every page for a signed-out
		// visitor, so asserting on the whole document would fail for a reason
		// that has nothing to do with the 401. The claim being tested is that
		// the ERROR does not tell anyone to sign in.
		await expect(
			error.getByRole('link', { name: /^(Masuk|Masuk kembali|Login)$/ })
		).toHaveCount(0);
		await expect(
			error.getByRole('button', { name: /^(Masuk|Masuk kembali|Login)$/ })
		).toHaveCount(0);

		// The form is still available to retry, which is the actionable thing
		// a mistyped code leaves behind.
		await expect(page.locator('#sigap-checkin-checkin_code')).toBeVisible();
	});

	test('offers the walk-in alternative for someone with no booking', async ({ page }) => {
		await page.goto('/appointments/check-in');
		const link = page.getByRole('link', { name: /Ambil antrean walk-in/i });
		await expect(link).toHaveAttribute('href', '/queues/new');
	});
});

/**
 * C. Status, looked up with a code the stack actually issued.
 *
 * The point is that the status page accepts what check-in produced. Two
 * separate writers of the same identifier agreeing is the whole contract, and
 * a fixture written by hand would prove nothing about it.
 */
test.describe('C. status', () => {
	test.use({ viewport: DESKTOP });

	test('finds the visit using the code the stack returned', async ({ page }) => {
		test.skip(!journey.checkinCode, 'A must produce a check-in code first');

		await page.goto('/patient/status');
		await page.locator('#sigap-status-code').fill(journey.checkinCode);
		await page.getByRole('button', { name: /Cek Status/ }).click();

		// A found result, backed by the seeded database.
		await expect(page.locator('[data-testid="visit-steps"]')).toBeVisible(SETTLE);
		await expect(page.locator('[data-testid="status-not-found"]')).toHaveCount(0);

		// The four frozen labels, and exactly one marked current.
		const steps = page.locator('.sigap-visit__step');
		await expect(steps).toHaveCount(4);
		for (const label of ['Check-In', 'Antre', 'Dilayani', 'Selesai']) {
			await expect(page.locator('.sigap-visit__step', { hasText: label }).first()).toBeVisible();
		}
		await expect(page.locator('[aria-current="step"]')).toHaveCount(1);

		// Current state only. The endpoint returns one status, not a history,
		// so any of these words would be the page inventing something about
		// someone's medical visit.
		const text = ((await page.locator('body').textContent()) ?? '').toLowerCase();
		for (const forbidden of [
			'realtime',
			'real-time',
			'live',
			'riwayat',
			'history',
			'durasi',
			'berjalan',
			'terus diperbarui'
		]) {
			expect(text, `the status page must not claim ${forbidden}`).not.toContain(forbidden);
		}
	});

	test('an unknown code is guidance, not an error', async ({ page }) => {
		await page.goto('/patient/status');
		await page.locator('#sigap-status-code').fill('NOSUCHCODE999');
		await page.getByRole('button', { name: /Cek Status/ }).click();

		// Not-found is its own state. Nothing is broken; the code is unknown.
		// And the page says what else could work.
		await expect(page.locator('[data-testid="status-not-found"]')).toBeVisible(SETTLE);
		await expect(page.locator('[data-testid="status-error"]')).toHaveCount(0);
		await expect(page.locator('body')).toContainText(/nomor antrean/i);
	});
});

/**
 * D. Walk-in, a separate transaction from check-in.
 *
 * Kept apart from A/B/C on purpose: it registers a new ticket for someone with
 * no booking, and merging it into the check-in flow would be exactly the
 * confusion the two routes exist to prevent.
 */
test.describe('D. walk-in', () => {
	test.use({ viewport: DESKTOP });

	test('registers a ticket for someone who arrived without a booking', async ({ page }) => {
		/*
		 * The facility list is the real public catalog, not a hardcoded list,
		 * and this is asserted EXACTLY — every catalog id offered, and nothing
		 * else.
		 *
		 * The comparison is taken against a snapshot that is stable across the
		 * page load. `admin-facility-mutations.spec.ts` CREATES and DEACTIVATES
		 * facilities, in another file on another worker against the same seeded
		 * database, so a catalog read taken after the page loaded can describe a
		 * different set than the page rendered. Reading before and after, and
		 * reloading until the two agree, is what makes the exact assertion
		 * honest rather than occasionally off by one.
		 */
		const catalogIds = async () => (await readFacilities(page)).map((f) => f.id).sort();

		let expected = await catalogIds();
		await page.goto('/queues/new');

		const facilitySelect = page.locator('#sigap-walkin-facilityId');
		for (let attempt = 0; attempt < 8; attempt += 1) {
			const afterLoad = await catalogIds();
			if (afterLoad.join(',') === expected.join(',')) break;
			// A create or deactivate landed in the window. Re-take the page
			// against the newer catalog so both describe the same set. `reload`
			// is already gated on hydration by the shared fixture.
			expected = afterLoad;
			await page.reload();
		}

		await expect(facilitySelect.locator('option')).toHaveCount(expected.length + 1, SETTLE);

		// Read the option values rather than trusting the shared `journey`
		// state. Two reasons: this is a self-contained transaction that does
		// not actually need A's facility, and a facility id that is somehow
		// absent from this list would make the select silently fall back to
		// the placeholder — the same confusing "option is not enabled"
		// failure that the serial grouping above exists to prevent.
		const optionValues = (
			await facilitySelect
				.locator('option')
				.evaluateAll((nodes) => nodes.map((node) => (node as HTMLOptionElement).value))
		).filter((value) => value !== '');
		expect(optionValues.length, 'the walk-in facility list must be populated').toBeGreaterThan(0);

		// The count alone would also be satisfied by a list that swapped one
		// real facility for another. The ids are what prove the select is
		// rendering the catalog rather than something that merely has its
		// cardinality.
		expect(
			[...optionValues].sort(),
			'the walk-in select must offer exactly the public catalog'
		).toEqual(expected);

		// Prefer the facility the booking used, since that is the one this
		// journey has already proven is real, and fall back to the first.
		const facilityId = optionValues.includes(journey.facilityId)
			? journey.facilityId
			: optionValues[0];
		await facilitySelect.selectOption(facilityId);

		await page.locator('#sigap-walkin-fullName').fill('Rina Marlina');
		await page.locator('#sigap-walkin-phone').fill(uniquePhone());

		/*
		 * A 5xx is a first-class test failure, not an accepted alternative.
		 * Register the response listener before clicking so the real backend
		 * result is observed even if the frontend immediately renders an error.
		 *
		 * The approved local stack includes the Rust queue engine. Booking and
		 * check-in can retry against FakeQueueService when that engine is absent,
		 * but the queue handler has no equivalent request-time fallback.
		 */
		const queueResponse = page.waitForResponse(
			(response) =>
				response.url().includes('/api/v1/queues/generate') &&
				response.request().method() === 'POST',
			{ timeout: SETTLE.timeout }
		);

		await page.getByRole('button', { name: /Ambil Nomor Antrean/ }).click();

		/*
		 * The backend MUST succeed. A 5xx here is a real infrastructure failure,
		 * not a state to assert around: the Rust queue engine is part of the
		 * authoritative local stack, so a 500 means the gRPC hop or the
		 * transactional counter is broken.
		 *
		 * Assert on the response as well as the rendered panel. A DOM-only
		 * assertion cannot distinguish a correctly rendered 500 from the required
		 * success state.
		 */
		const generated = await queueResponse;
		expect(
			generated.status(),
			'POST /api/v1/queues/generate must succeed. A 5xx means the Rust queue engine is not ' +
				'reachable from the Go API: check that it is listening on the port in SIGAP_ENGINE_ADDR ' +
				'and that /readyz reports ready before the suite starts.'
		).toBe(200);

		const body = (await generated.json()) as {
			success?: boolean;
			data?: {
				formatted_number?: string;
				FormattedNumber?: string;
				estimated_wait_minutes?: number;
			};
			error?: string;
		};
		expect(body.success, `the engine answered with: ${JSON.stringify(body)}`).toBe(true);

		// The wire accepts either casing, so assert through the normalized value
		// the UI actually reads. Both spellings have deterministic unit coverage.
		const wireNumber = body.data?.formatted_number ?? body.data?.FormattedNumber ?? '';
		expect(wireNumber, 'the engine must return a formatted queue number').not.toBe('');

		const number = page.locator('[data-testid="walkin-number"]');
		await expect(number).toBeVisible(SETTLE);

		// The number shown is the number the backend issued. A success panel that
		// renders a different value would silently send a citizen to the wrong
		// place in the queue.
		const displayed = ((await number.textContent()) ?? '').trim();
		expect(displayed.length, 'a formatted queue number must be shown').toBeGreaterThan(0);
		expect(displayed).not.toBe('-');
		expect(displayed, 'the displayed number must be the one the engine issued').toBe(wireNumber);
		expect(displayed, 'the real engine formats the number from the facility short code').toMatch(
			/^[A-Z]{2,4}-\d{4,}$/
		);

		// The estimate is labelled as an estimate. The backend computes it once
		// at generation, so presenting it as current would overstate the system.
		const text = ((await page.locator('body').textContent()) ?? '').toLowerCase();
		expect(text).toContain('estimasi');
		for (const forbidden of ['realtime', 'real-time', 'live', 'dipastikan', 'pasti']) {
			expect(text, `walk-in must not claim ${forbidden}`).not.toContain(forbidden);
		}

		// The way onward, now that there is a number to check on.
		await expect(
			page.getByRole('link', { name: /Cek status kunjungan/i })
		).toHaveAttribute('href', '/patient/status');
		await expect(page.locator('[data-testid="walkin-error"]')).toHaveCount(0);

		// The booking-code route remains available as the alternative for a
		// citizen who did not arrive as a walk-in.
		await expect(
			page.getByRole('link', { name: /Gunakan kode check-in/i })
		).toHaveAttribute('href', '/appointments/check-in');
	});

	test('rejects a walk-in without a facility before calling the backend', async ({ page }) => {
		await page.goto('/queues/new');

		const posted: string[] = [];
		page.on('request', (request) => {
			if (request.method() === 'POST') posted.push(request.url());
		});

		await page.getByRole('button', { name: /Ambil Nomor Antrean/ }).click();

		// Inline validation, and nothing was sent. The daily limiter is keyed
		// on phone and facility, so a request with neither would consume a
		// malformed rate-limit slot.
		await expect(page.locator('body')).toContainText(/wajib diisi/i);
		expect(posted, 'validation must gate the request').toHaveLength(0);
	});
}); // end describe 'D. walk-in'
}); // end describe.serial 'the citizen transactions, end to end'

/**
 * Responsive and accessibility, at both ends of the range.
 *
 * Automated rather than left to review because these are the defects that
 * survive a code review and fail on a real phone. Every page is checked at
 * 390px and 1440px for sideways scroll, because a two-column booking form is
 * the most likely thing in this phase to overflow a narrow screen.
 *
 * These are NOT inside the serial group. They are independent per page, so
 * running them in parallel with the transaction chain costs nothing in
 * correctness and keeps the suite's wall time down.
 */
test.describe('responsive and accessibility', () => {
	const ROUTES = [
		'/appointments/new',
		'/appointments/check-in',
		'/queues/new',
		'/patient/status',
		'/auth/login',
		'/auth/register',
		'/auth/logout'
	];

	for (const viewport of [MOBILE, DESKTOP]) {
		test.describe(`${viewport.width}px`, () => {
			test.use({ viewport });

			for (const route of ROUTES) {
				test(`${route} does not overflow horizontally`, async ({ page }) => {
					await page.goto(route);
					await expect(page.getByRole('heading', { level: 1 })).toBeVisible(SETTLE);
					await expectNoHorizontalOverflow(page);
				});

				test(`${route} has exactly one h1`, async ({ page }) => {
					await page.goto(route);
					await expect(page.getByRole('heading', { level: 1 })).toBeVisible(SETTLE);
					await expect(page.getByRole('heading', { level: 1 })).toHaveCount(1);
				});
			}

			test('the bottom navigation never covers the end of a long form', async ({ page }) => {
				await page.goto('/appointments/new');
				await expect(page.getByRole('heading', { level: 1 })).toBeVisible(SETTLE);
				// Only the mobile shell has the fixed bar; asserting the
				// clearance unconditionally would fail on desktop for the
				// right reason and the wrong message.
				if ((await page.locator('nav.sigap-bottom-nav').count()) > 0) {
					await expectContentClearsBottomNav(page);
				}
			});

			test('the booking stepper is not clipped', async ({ page }) => {
				await page.goto('/appointments/new');
				const stepper = page.locator('.sigap-stepper');
				await expect(stepper).toBeVisible(SETTLE);
				// Clipping is the failure: a step whose label is cut off tells a
				// citizen the form is longer than it is, and hides which step
				// they are on.
				for (const label of ['Fasilitas', 'Layanan', 'Waktu + Data Diri']) {
					const item = stepper.locator('li', { hasText: label });
					await expect(item).toBeVisible();
					const clipped = await item.evaluate((el) => {
						const style = getComputedStyle(el);
						return (
							style.overflow === 'hidden' &&
							el.scrollHeight > el.clientHeight + 1
						);
					});
					expect(clipped, `the "${label}" step must not be clipped`).toBe(false);
				}
			});

			test('every form control meets the 44px touch floor', async ({ page }) => {
				for (const route of ['/appointments/new', '/queues/new', '/patient/status', '/auth/login', '/auth/register']) {
					await page.goto(route);
					await expect(page.getByRole('heading', { level: 1 })).toBeVisible(SETTLE);

					// The catalog-backed pages render their form disabled while
					// loading, and a disabled control is skipped by the
					// visibility filter below. Waiting for one to be enabled
					// means the measurement happens on the settled form, not on
					// a loading state that happens to be fully sized.
					const firstInput = page.locator('input:not([type="hidden"])').first();
					if ((await firstInput.count()) > 0) {
						await expect(firstInput).toBeEnabled({ timeout: 10_000 }).catch(() => {
							// A genuinely static form (the auth pages) has nothing
							// to wait for, which is not a failure.
						});
					}

					const heights = await page
						.locator('input:not([type="hidden"]), select, textarea, button[type="submit"]')
						.evaluateAll((nodes) =>
							nodes
								.filter((node) => (node as HTMLElement).offsetParent !== null)
								.map((node) => ({
									tag: (node as HTMLElement).tagName,
									id: (node as HTMLElement).id,
									height: node.getBoundingClientRect().height
								}))
						);
					for (const control of heights) {
						expect(
							control.height,
							`${control.tag}#${control.id} is ${control.height}px tall on ${route}`
						).toBeGreaterThanOrEqual(44);
					}
				}
			});

			test('form controls show a visible focus ring', async ({ page }) => {
				await page.goto('/queues/new');
				await expect(page.getByRole('heading', { level: 1 })).toBeVisible(SETTLE);

				/*
				 * Waits for the control to stop being disabled, not merely to
				 * exist. The walk-in form is disabled while the public catalog
				 * loads, because a facility cannot be chosen from an empty
				 * list. Focusing a disabled input is a no-op, so a test that
				 * focuses on sight would read "inactive" and look like a
				 * missing focus ring when the real cause is that the page had
				 * not finished loading — the same class of false failure the
				 * walk-in unit tests hit.
				 */
				const input = page.locator('#sigap-walkin-fullName');
				await expect(input).toBeEnabled({ timeout: 10_000 });
				await input.focus();
				await expect(input).toBeFocused();

				// A ring that is present but zero-width is the same as no ring
				// for a keyboard user.
				const outline = await input.evaluate((el) => {
					const style = getComputedStyle(el);
					return { width: style.outlineWidth, style: style.outlineStyle };
				});
				expect(parseFloat(outline.width)).toBeGreaterThan(0);
				expect(outline.style).not.toBe('none');
			});
		});
	}
});

/**
 * The transactions stay inside the local origin.
 *
 * The same property the 3B2 suite proves for browsing, extended to the flows
 * that actually POST. A transactional test is the one most likely to acquire
 * an absolute URL somewhere, so this is where it would show up.
 *
 * Deliberately independent of the `journey` chain. This is a property of the
 * ROUTES rather than of one particular appointment, so making it depend on
 * state produced three suites away would turn a routing guarantee into a
 * scheduling one — and if the chain were reordered, this test would start
 * skipping for reasons that have nothing to do with what it checks.
 */
test.describe('the transactions stay local', () => {
	test.use({ viewport: DESKTOP });

	test('check-in, walk-in, and status never leave the local origin', async ({
		page,
		baseURL
	}) => {
		const requested: string[] = [];
		page.on('request', (request) => requested.push(request.url()));

		// A fabricated identifier: the request is made and fails, which is
		// what exercises the proxy. No real record is needed to prove that the
		// browser is not calling out to a production host.
		await page.goto(
			'/appointments/check-in?appointment_id=00000000-0000-4000-8000-000000000000&checkin_code=LOCALONLY1'
		);
		await expect(page.locator('h1')).toBeVisible(SETTLE);

		await page.goto('/patient/status');
		await expect(page.locator('h1')).toBeVisible(SETTLE);

		await page.goto('/queues/new');
		await expect(page.locator('h1')).toBeVisible(SETTLE);

		const host = new URL(baseURL as string).host;
		expect(requested.length, 'the pages must actually have made requests').toBeGreaterThan(0);
		for (const url of requested) {
			expect(url, `${url} must stay on the local origin`).toContain(host);
			expect(url, `${url} must not reach production`).not.toContain('chaerulchalik');
		}
	});
});
